### ISSUE TITLE
Campo headquarter necesario en userSchema

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/schemas#6]
Necesitamos saber el campus o headquarter de un usuario para poder hacer nuestro sistema. Es distinto que un cohort puesto que muchos usuarios no tendrán un cohort asociado (laboratorians por ejemplo). Así podemos identificar de manera correcta donde pertenece cada quien.

CC: @AnaSalazar

**Comment by lupomontero** [comment]
Esto me da la impresión que es algo que podemos _inferir_ de data que ya tenemos... en la colección `users` tenemos el `signupCohort` de cada estudiante, y cada cohort está asignado a una sede... si hubiera (que creo que hay) casos donde no hay `signupCohort` igual podemos inferir el campus (sede) a través de los cohorts... :thinking:

**Comment by bouli** [comment]
Se puede acceder la info través de los cohorts. La idea es que un user pueda pertenecer a más de un cohort. i.e. alguién que inicia el bootcamp en CDMX y puede ir a Guadalajara.
